apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: backend
          image: oluwademilade/shopeasy-backend:v4.3

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: shopeasy-config
            - secretRef:
                name: shopeasy-secrets

          volumeMounts:
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tmp
          emptyDir: {}
