apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
spec:
  replicas: 0
  selector:
    matchLabels:
      app: frontend
      version: v4.6
  template:
    metadata:
      labels:
        app: frontend
        version: v4.6
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: frontend
          image: oluwademilade/shopeasy-frontend:v4.6

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 8080

          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: nginx-tmp
              mountPath: /tmp

      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: nginx-tmp
          emptyDir: {}
